// <auto-generated />
using System;
using BankingSystem.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingSystem.Data.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    partial class BankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("BankingSystem.Data.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountNumber = "ACC-10001",
                            AccountType = 1,
                            Balance = 1750.00m,
                            CustomerId = 1
                        },
                        new
                        {
                            AccountId = 2,
                            AccountNumber = "ACC-10002",
                            AccountType = 2,
                            Balance = 4200.00m,
                            CustomerId = 1
                        },
                        new
                        {
                            AccountId = 3,
                            AccountNumber = "ACC-10003",
                            AccountType = 1,
                            Balance = 980.50m,
                            CustomerId = 2
                        });
                });

            modelBuilder.Entity("BankingSystem.Data.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            DateOfBirth = new DateTime(1990, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.carter@example.com",
                            FirstName = "John",
                            LastName = "Carter"
                        },
                        new
                        {
                            CustomerId = 2,
                            DateOfBirth = new DateTime(1987, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.singh@example.com",
                            FirstName = "Maria",
                            LastName = "Singh"
                        });
                });

            modelBuilder.Entity("BankingSystem.Data.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountId = 1,
                            Amount = 1500.00m,
                            BalanceAfter = 1500.00m,
                            Description = "Initial deposit",
                            TransactionDate = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountId = 1,
                            Amount = 250.00m,
                            BalanceAfter = 1750.00m,
                            Description = "Paycheck top-up",
                            TransactionDate = new DateTime(2026, 4, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountId = 2,
                            Amount = 4200.00m,
                            BalanceAfter = 4200.00m,
                            Description = "Savings opening balance",
                            TransactionDate = new DateTime(2026, 4, 5, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountId = 3,
                            Amount = 1000.00m,
                            BalanceAfter = 1000.00m,
                            Description = "Initial deposit",
                            TransactionDate = new DateTime(2026, 4, 2, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 1
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountId = 3,
                            Amount = 19.50m,
                            BalanceAfter = 980.50m,
                            Description = "ATM cash withdrawal",
                            TransactionDate = new DateTime(2026, 4, 20, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = 2
                        });
                });

            modelBuilder.Entity("BankingSystem.Data.Models.Account", b =>
                {
                    b.HasOne("BankingSystem.Data.Models.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BankingSystem.Data.Models.Transaction", b =>
                {
                    b.HasOne("BankingSystem.Data.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankingSystem.Data.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankingSystem.Data.Models.Customer", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
